<a href="https://colab.research.google.com/github/kirankumar49460/kirankumargajjala_ai/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

print(torch.__version__)
print(torch.cuda.is_available())

2.9.0+cu126
True


In [ ]:
tensor1 = torch.tensor([[10,11,12,13,14],[15,16,17,18,19]])
tensor2 = torch.tensor([[22,23,24,25,26],[27,28,29,30,31]])
sum_tensors = tensor1 + tensor2
print(sum_tensors)
print(tensor1.size())


tensor([[32, 34, 36, 38, 40],
        [42, 44, 46, 48, 50]])
torch.Size([2, 5])


In [ ]:
sub_tensors = tensor1 - tensor2
print(sub_tensors)
print(sub_tensors.size())

tensor([[-12, -12, -12, -12, -12],
        [-12, -12, -12, -12, -12]])
torch.Size([2, 5])


In [5]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
print(device)

cuda


In [7]:
tensor1 = torch.tensor([[10,11,12,13,14],[15,16,17,18,19]], device=device)
tensor2 = torch.tensor([[22,23,24,25,26],[27,28,29,30,31]], device=device)
multi_tensors = tensor1 * tensor2
print(multi_tensors)

tensor([[220, 253, 288, 325, 364],
        [405, 448, 493, 540, 589]], device='cuda:0')


In [11]:
tensor_fromlist = torch.tensor([1,2,3,4,5])
tensor_fromtuple = torch.tensor((1,2,3,4,5))
print(tensor_fromlist)
print(tensor_fromtuple)
tensor_fromarray = torch.tensor(np.array([1,2,3,4,5]))
print(tensor_fromarray )

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


In [12]:
tensor_empty = torch.empty(3,4)
tensor_ones = torch.ones(3,4)
tensor_zeros = torch.zeros(3,4)
print(tensor_empty)
print(tensor_ones)
print(tensor_zeros)

tensor([[ 1.5224e-38,  0.0000e+00,  1.5224e-38,  0.0000e+00],
        [ 1.5224e-38,  0.0000e+00,  1.6343e-38,  0.0000e+00],
        [ 1.6343e-38,  0.0000e+00, -4.5957e+29,  4.3234e-41]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
tensor_random = torch.rand(3,4)
print(tensor_random)
tensor_randn = torch.randn(3,4)
print(tensor_randn)
tensor_randint = torch.randint(1,6,(3,4))
print(tensor_randint)

tensor([[0.9123, 0.4288, 0.8010, 0.5690],
        [0.3348, 0.8042, 0.8684, 0.1872],
        [0.0131, 0.6874, 0.5947, 0.3314]])
tensor([[ 0.2908, -0.4608,  0.4213,  0.1865],
        [ 0.6905,  0.4752, -1.3034,  0.3766],
        [-0.5674,  0.3885, -0.8020, -0.1905]])
tensor([[3, 2, 3, 1],
        [4, 2, 1, 1],
        [3, 5, 4, 4]])


In [14]:
tensor_like = torch.ones_like(tensor_random) # uses same props like dtype, device etc
print(tensor_like)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [20]:
print(tensor1.dtype)
print(tensor1.device)
print(tensor1.ndim)
print(tensor1.shape)

torch.int64
cuda:0
2
torch.Size([2, 5])


In [6]:
tensor_int16 = torch.tensor([1,2], dtype=torch.int16)
print(tensor_int16.dtype)
tensor_int16 = tensor_int16.float()
print(tensor_int16.dtype)
tensor_int16 = tensor_int16.to(dtype=torch.int8)
print(tensor_int16.dtype)

torch.int16
torch.float32
torch.int8


In [11]:
tensor_like = torch.full_like(tensor_random,5)
print(tensor_like)
tensor_like = torch.full((3,4),5)
print(tensor_like)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [2]:
tensor_onedim = torch.tensor([1,2,3,4,5,6,7,8])
print(tensor_onedim[2])
print(tensor_onedim[2:5])
print(tensor_onedim[2:8:2]) # with step of 2

tensor(3)
tensor([3, 4, 5])
tensor([3, 5, 7])


In [7]:
tensor_twodim = torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[13,14,15,16,17,18]])
print(tensor_twodim)
print(tensor_twodim[1,3])
print(tensor_twodim[0,0:3]) # first 3 elements of 1st row
print(tensor_twodim[0:2,0:4]) #  first 4 elements of 2 rows

print(tensor_twodim[tensor_twodim<5]) # print all the elements which are less than 5

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [13, 14, 15, 16, 17, 18]])
tensor(10)
tensor([1, 2, 3])
tensor([[ 1,  2,  3,  4],
        [ 7,  8,  9, 10]])
tensor([1, 2, 3, 4])


In [10]:
#combile tensors
tensor_combine = torch.stack((tensor_twodim, tensor_twodim))
print(tensor_combine)

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [13, 14, 15, 16, 17, 18]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [13, 14, 15, 16, 17, 18]]])


In [16]:
# unbind tensor
print(tensor_twodim.unbind())
# assign it to variables
first_tensor, second_tensor, third_tensor, fourth_tensor = torch.unbind(tensor_twodim)
print(first_tensor)
print(second_tensor)
print(third_tensor)
print(fourth_tensor)

#unbine in columns 0 - rows, 1 - columns
first_tensor, second_tensor, third_tensor, fourth_tensor, fifth_tensor, sixth_tensor = torch.unbind(tensor_twodim, dim=1)
print(first_tensor)
print(second_tensor)
print(third_tensor)
print(fourth_tensor)
print(fifth_tensor)
print(sixth_tensor)

(tensor([1, 2, 3, 4, 5, 6]), tensor([ 7,  8,  9, 10, 11, 12]), tensor([13, 14, 15, 16, 17, 18]), tensor([13, 14, 15, 16, 17, 18]))
tensor([1, 2, 3, 4, 5, 6])
tensor([ 7,  8,  9, 10, 11, 12])
tensor([13, 14, 15, 16, 17, 18])
tensor([13, 14, 15, 16, 17, 18])
tensor([ 1,  7, 13, 13])
tensor([ 2,  8, 14, 14])
tensor([ 3,  9, 15, 15])
tensor([ 4, 10, 16, 16])
tensor([ 5, 11, 17, 17])
tensor([ 6, 12, 18, 18])
