<a href="https://colab.research.google.com/github/kirankumar49460/kirankumargajjala_ai/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import numpy as np

print(torch.__version__)
print(torch.cuda.is_available())

2.9.0+cu126
True


In [ ]:
tensor1 = torch.tensor([[10,11,12,13,14],[15,16,17,18,19]])
tensor2 = torch.tensor([[22,23,24,25,26],[27,28,29,30,31]])
sum_tensors = tensor1 + tensor2
print(sum_tensors)
print(tensor1.size())


tensor([[32, 34, 36, 38, 40],
        [42, 44, 46, 48, 50]])
torch.Size([2, 5])


In [ ]:
sub_tensors = tensor1 - tensor2
print(sub_tensors)
print(sub_tensors.size())

tensor([[-12, -12, -12, -12, -12],
        [-12, -12, -12, -12, -12]])
torch.Size([2, 5])


In [5]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
print(device)

cuda


In [7]:
tensor1 = torch.tensor([[10,11,12,13,14],[15,16,17,18,19]], device=device)
tensor2 = torch.tensor([[22,23,24,25,26],[27,28,29,30,31]], device=device)
multi_tensors = tensor1 * tensor2
print(multi_tensors)

tensor([[220, 253, 288, 325, 364],
        [405, 448, 493, 540, 589]], device='cuda:0')


In [11]:
tensor_fromlist = torch.tensor([1,2,3,4,5])
tensor_fromtuple = torch.tensor((1,2,3,4,5))
print(tensor_fromlist)
print(tensor_fromtuple)
tensor_fromarray = torch.tensor(np.array([1,2,3,4,5]))
print(tensor_fromarray )

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


In [12]:
tensor_empty = torch.empty(3,4)
tensor_ones = torch.ones(3,4)
tensor_zeros = torch.zeros(3,4)
print(tensor_empty)
print(tensor_ones)
print(tensor_zeros)

tensor([[ 1.5224e-38,  0.0000e+00,  1.5224e-38,  0.0000e+00],
        [ 1.5224e-38,  0.0000e+00,  1.6343e-38,  0.0000e+00],
        [ 1.6343e-38,  0.0000e+00, -4.5957e+29,  4.3234e-41]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [13]:
tensor_random = torch.rand(3,4)
print(tensor_random)
tensor_randn = torch.randn(3,4)
print(tensor_randn)
tensor_randint = torch.randint(1,6,(3,4))
print(tensor_randint)

tensor([[0.1210, 0.0753, 0.8482, 0.1143],
        [0.2059, 0.5501, 0.9670, 0.6170],
        [0.0641, 0.2128, 0.7271, 0.2370]])
tensor([[-0.4368,  0.3947,  1.5519,  0.5681],
        [-0.5714, -0.5170, -1.5133, -0.8854],
        [-0.3014,  0.2556,  1.3624, -1.6050]])
tensor([[5, 5, 4, 5],
        [3, 2, 4, 1],
        [1, 1, 5, 5]])


In [14]:
tensor_like = torch.ones_like(tensor_random) # uses same props like dtype, device etc
print(tensor_like)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [20]:
print(tensor1.dtype)
print(tensor1.device)
print(tensor1.ndim)
print(tensor1.shape)

torch.int64
cuda:0
2
torch.Size([2, 5])


In [21]:
tensor_int16 = torch.tensor([1,2], dtype=torch.int16)
print(tensor_int16.dtype)
tensor

torch.int16
